version: "3.9"

services:
  lukso-validator-testnet:
    image: gcr.io/abacus-labs-dev/hyperlane-agent:agents-v1.4.0
    command: ./validator
    container_name: lukso-validator-testnet
    environment:
      - CONFIG_FILES=/config/config-agents.json
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /home/magali/config-agents.json:/config/config-agents.json:ro
    restart: unless-stopped
